Algoritmo "Ex14"

Var 
indicePoluicao : real

Inicio
escreva("Indice de poluicao: ")
leia(indicePoluicao)

se indicePoluicao = 0.3 entao
  escreval("Grupo 1 - Intimados e atividades paradas")
fimse

se indicePoluicao = 0.4 entao
  escreval("Grupo 1 e 2 - Intimados e atividade paradas ")
fimse

se indicePoluicao = 0.5 entao
  escreval("Todos os grupos - Intimados e atividade paradas")
fimse

Fimalgoritmo
